# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mithro rants about stuff
email: tim@mithis.net
description: >- # this means to ignore newlines until "baseurl:"
  Technical blog about open source hardware, software development, and tech projects.
  Documenting work on HDMI2USB, TimVideos.us, and various hardware/software initiatives.
baseurl: "/blog.mithis.net" # the subpath of your site, e.g. /blog
url: "https://mithro.github.io" # the base hostname & protocol for your site
github_username: mithro

# Build settings
# theme: minima  # Removed for now - will use custom Barthelme theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Permalink structure - individual permalinks set in each post front matter
# permalink: /:year/:month/:title/  # Disabled - using WordPress-compatible permalinks

# Timezone
timezone: America/Los_Angeles

# Google Analytics
google_analytics: UA-XXXXXXXX-X  # Replace with actual tracking ID

# Pagination
paginate: 10

# Feed configuration
feed:
  path: "/feed/index.xml"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  tutorials:
    output: true
    permalink: /:collection/:name/
  hardware:
    output: true
    permalink: /:collection/:name/

# Markdown processor
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
